# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 441)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 441))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 800))
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgb(150, 150, 150);")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(20, 160, 61, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: rgb(115, 115, 115);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(350, 90, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color: rgb(70, 70, 70);")
        self.label1.setObjectName("label1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 30, 421, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_kalanhak = QtWidgets.QLabel(self.centralwidget)
        self.txt_kalanhak.setGeometry(QtCore.QRect(470, 90, 47, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_kalanhak.setFont(font)
        self.txt_kalanhak.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_kalanhak.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_kalanhak.setText("")
        self.txt_kalanhak.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_kalanhak.setObjectName("txt_kalanhak")
        self.txt_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.txt_sonuc.setGeometry(QtCore.QRect(80, 150, 501, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_sonuc.setFont(font)
        self.txt_sonuc.setStyleSheet("background-color: rgb(182, 182, 182);")
        self.txt_sonuc.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_sonuc.setText("")
        self.txt_sonuc.setWordWrap(True)
        self.txt_sonuc.setObjectName("txt_sonuc")
        self.txt_tahmin = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_tahmin.setGeometry(QtCore.QRect(200, 90, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_tahmin.sizePolicy().hasHeightForWidth())
        self.txt_tahmin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_tahmin.setFont(font)
        self.txt_tahmin.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.txt_tahmin.setObjectName("txt_tahmin")
        self.btn_yenioyun = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yenioyun.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.btn_cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis.setGeometry(QtCore.QRect(20, 240, 81, 31))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_yenioyun.sizePolicy().hasHeightForWidth())
        self.btn_yenioyun.setSizePolicy(sizePolicy)
        sizePolicy.setHeightForWidth(self.btn_cikis.sizePolicy().hasHeightForWidth())
        self.btn_cikis.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_yenioyun.setFont(font)
        self.btn_yenioyun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_yenioyun.setIconSize(QtCore.QSize(20, 20))
        self.btn_yenioyun.setObjectName("btn_yenioyun")
        self.btn_cikis.setFont(font)
        self.btn_cikis.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_cikis.setIconSize(QtCore.QSize(20, 20))
        self.btn_cikis.setObjectName("btn_cikis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sayı Tahmin Oyunu"))
        self.label.setText(_translate("MainWindow", "Tahmin ettiğiniz sayıyı sağdaki kutucuğa giriniz"))
        self.label2.setText(_translate("MainWindow", "Sonuç: "))
        self.label1.setText(_translate("MainWindow", "Kalan Hakkınız"))
        self.label_4.setText(_translate("MainWindow", "1 ile 100 arasında bilgisayarın tahmin ettiği sayıyı bulmak için oyuna başla"))
        self.btn_yenioyun.setText(_translate("MainWindow", "Yeni Oyun"))
        self.btn_cikis.setText(_translate("MainWindow", "Cikis"))

import icons_rc
